
package telemedicinesystem;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class MakeAnAppointment extends javax.swing.JFrame {

    /**
     * Creates new form ProfilePage
     */
    public MakeAnAppointment(int did, int pid) {
        initComponents();
        setBackground(new Color(0,0,0,0));
        createConnection();
        this.did=did;
        this.pid=pid;
        p1.setVisible(false);
    }
    
    public void createConnection()
    {
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Telemedicine","root","root");
            }
        catch(Exception e)
        {
            
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        p4 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        dcontact = new javax.swing.JLabel();
        dname = new javax.swing.JLabel();
        treated = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        dname2 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        m1 = new javax.swing.JComboBox<>();
        service = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        dname3 = new javax.swing.JLabel();
        h1 = new javax.swing.JComboBox<>();
        dname4 = new javax.swing.JLabel();
        dname5 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        p3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("*");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel7.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(0,0,0,180));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(225, 162, 81), new java.awt.Color(225, 162, 81)));
        jPanel1.setToolTipText("");

        p4.setBackground(new java.awt.Color(0,0,0,40));
        p4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(204, 204, 204));
        jLabel50.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 204));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Schedule an Appointment");
        jLabel50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        p4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 540, 30));

        p5.setBackground(new java.awt.Color(0,0,0,40));
        p5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dcontact.setBackground(new java.awt.Color(204, 204, 204));
        dcontact.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        dcontact.setForeground(new java.awt.Color(255, 255, 255));
        dcontact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.add(dcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 30));

        dname.setBackground(new java.awt.Color(204, 204, 204));
        dname.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        dname.setForeground(new java.awt.Color(255, 255, 255));
        dname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.add(dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 30));

        treated.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        treated.setForeground(new java.awt.Color(255, 255, 255));
        treated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.add(treated, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 540, 30));

        p4.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 540, 110));

        p1.setBackground(new java.awt.Color(0,0,0,40));
        p1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dname2.setBackground(new java.awt.Color(204, 204, 204));
        dname2.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        dname2.setForeground(new java.awt.Color(255, 255, 255));
        dname2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dname2.setText("Appointment Date");
        p1.add(dname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 30));

        date.setDateFormatString("YYYY-MM-dd");
        date.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        p1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 210, 30));

        m1.setBackground(new java.awt.Color(0,0,0,180));
        m1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 255, 255));
        m1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Min", "00", "30", " ", " ", " ", " ", " ", " ", " ", " " }));
        m1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m1ActionPerformed(evt);
            }
        });
        p1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 100, -1));

        service.setBackground(new java.awt.Color(0,0,0,180));
        service.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        service.setForeground(new java.awt.Color(255, 255, 255));
        service.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Service" }));
        service.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        service.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                serviceItemStateChanged(evt);
            }
        });
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        p1.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 210, -1));

        jLabel51.setBackground(new java.awt.Color(204, 204, 204));
        jLabel51.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 204, 204));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Make an Appointment");
        jLabel51.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });
        p1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 520, 30));

        dname3.setBackground(new java.awt.Color(204, 204, 204));
        dname3.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        dname3.setForeground(new java.awt.Color(255, 255, 255));
        dname3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dname3.setText("Appointment Time");
        p1.add(dname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, 30));

        h1.setBackground(new java.awt.Color(0,0,0,180));
        h1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        h1.setForeground(new java.awt.Color(255, 255, 255));
        h1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hour", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" }));
        h1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        p1.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 100, -1));

        dname4.setBackground(new java.awt.Color(204, 204, 204));
        dname4.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        dname4.setForeground(new java.awt.Color(255, 255, 255));
        dname4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dname4.setText("Service");
        p1.add(dname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 30));

        dname5.setBackground(new java.awt.Color(204, 204, 204));
        dname5.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        dname5.setForeground(new java.awt.Color(255, 255, 255));
        dname5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dname5.setText("Amount");
        p1.add(dname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 30));

        amountfield.setEditable(false);
        amountfield.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        amountfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.add(amountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 142, 210, 30));

        p4.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 540, 230));

        jPanel2.setBackground(new java.awt.Color(0,0,0,50));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 255), null, null));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p3.setBackground(new java.awt.Color(0,0,0,0));
        p3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        p3.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 3, -1, 34));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xx,yy;      
int did=0, pid=0;
Connection con;
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select Fname, Mname, Lname, Contact from Doctor where Doctor_ID="+did+"");
            while(rs.next())
            {
                dname.setText(rs.getString("Fname")+" "+rs.getString("Mname")+" "+rs.getString("Lname"));
                dcontact.setText(rs.getString("Contact"));
            }
            
            ResultSet rs1=st.executeQuery("select count(*) from appointment where Doctor_ID="+did+" and Date<(select curdate());");
            while(rs1.next())
            {
                treated.setText("Treated: "+rs1.getString("Count(*)")+" Patients");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        try
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select distinct(Service_Name) from Services");
            while(rs.next())
            {
                service.addItem(rs.getString("Service_Name"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        p3.setBackground(Color.black);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        p3.setBackground(new Color(232,17,36,255));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
    p1.setVisible(true);
    }//GEN-LAST:event_jLabel50MouseClicked
int sid=0;
    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
    String adate=((JTextField)date.getDateEditor().getUiComponent()).getText();
    int amount=Integer.parseInt(amountfield.getText());
    String time=hour+":"+min+":00";
    int count=0;
    try
    {
        Statement st=con.createStatement();
        ResultSet rs1=st.executeQuery("select count(*) from Appointment where Time='"+time+"' and Date='"+adate+"'and Doctor_ID="+did+"");
        while(rs1.next())
        {
            count=rs1.getInt("Count(*)");
        }
        if(count==0){
            ResultSet rs=st.executeQuery("Select Service_ID from Services where Service_Name='"+selectedservice+"'");
            while(rs.next())
            {
                sid=rs.getInt("Service_ID");
            }
            st.executeUpdate("insert into Appointment(Doctor_ID, Service_ID,Appointment_Status,Amount,Date,Time,Patient_ID) values("+did+","+sid+",'Accepted',"+amount+",'"+adate+"','"+time+"',"+pid+")");
            JOptionPane.showMessageDialog(null,"Appointment Scheduled Successfully");
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Sorry, Slot is Already Booked");
        }
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
    }//GEN-LAST:event_jLabel51MouseClicked
String selectedservice="";
    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        try
        {
            selectedservice=service.getSelectedItem().toString();   
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select Amount from Services where Service_Name='"+selectedservice+"'");
            while(rs.next())
            {
                amountfield.setText("");
                amountfield.setText(""+rs.getInt("Amount"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_serviceActionPerformed

    private void serviceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_serviceItemStateChanged

    }//GEN-LAST:event_serviceItemStateChanged

String hour, min;
    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        hour=(String)h1.getSelectedItem();
    }//GEN-LAST:event_h1ActionPerformed

    private void m1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m1ActionPerformed
        min=(String)m1.getSelectedItem();
    }//GEN-LAST:event_m1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAnAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAnAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAnAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAnAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeAnAppointment(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountfield;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel dcontact;
    private javax.swing.JLabel dname;
    private javax.swing.JLabel dname2;
    private javax.swing.JLabel dname3;
    private javax.swing.JLabel dname4;
    private javax.swing.JLabel dname5;
    private javax.swing.JComboBox<String> h1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> m1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JComboBox<String> service;
    private javax.swing.JLabel treated;
    // End of variables declaration//GEN-END:variables
}
